const productos = [
    {
        id: 1,
        nombre: "Hidrolavadora Karcher K3",
        precio: 90000,
        img: "https://http2.mlstatic.com/D_NQ_NP_2X_943957-MLA53134745936_012023-F.webp",
        descripcion: "La nueva Hidrolavadora K3 Power Control es ideal para un uso ocasional contra la suciedad ligera. Ajusta el nivel de presión en la lanza pulverizadora y controla la presión en el indicador de la pistola de alta presión G 120 Q Full Control para obtener la máxima visualización y aplicar la presión ideal en cada superficie u objeto. Gracias a la empuñadura y las ruedas, se puede maniobrar perfectamente y así se puede utilizar de forma flexible.",
        // categoria: ,
    },
    {
        id: 2,
        nombre: "Pulidora Roto Orbital Vonixx Voxer",
        precio: 245000,
        img: "https://http2.mlstatic.com/D_NQ_NP_2X_651628-MLA52536768071_112022-F.webp",
        descripcion: "Máquinas con baja emisión de ruido, alta calidad, durabilidad, equilibrio perfecto y los mejores rodamientos del mercado de la marca NSK, y escobillas de carbón japonesas Toyo. Las máquinas tienen un diseño que es único para nosotros, diseñado para satisfacer las mayores solicitudes de los clientes para un uso profesional y exclusivo de Vonixx.",
    },
    {
        id: 3,
        nombre: "Pulidora Rotativa 3d L-36",
        precio: 75000,
        img: "https://http2.mlstatic.com/D_NQ_NP_972795-MLA50238879707_062022-O.webp",
        descripcion: "Es una excelente máquina para detailers y hobbistas, muy liviana, cómoda y fácil de maniobrar velocidad digital modificable con botones + /- y botón on/off lo que la hace todavía mas cómoda a la hora de usarla.",
    },
    {
        id: 4,
        nombre: "Aspiradora Industrial Elsea",
        precio: 145000,
        img: "https://cdn.shopify.com/s/files/1/0615/3633/8147/products/ARESPLUS_001_Dammsugarevat_torr37liter.jpg?v=1664791796",
        descripcion: "Descubre la potencia y eficiencia de la aspiradora industrial de polvo líquido Elsea Egeco. Con su motor de 1100 vatios y una capacidad de 37 litros, esta máquina robusta es perfecta para hacer frente a los desafíos de limpieza más exigentes.",
    },
    {
        id: 5,
        nombre: "Kit Pulido 3 Pasos Menzerna 250ml",
        precio: 36500,
        img: "https://http2.mlstatic.com/D_NQ_NP_2X_603024-MLA54263567578_032023-F.webp",
        descripcion: `Kit Menzerna 3 pasos 250ml: MENZERNA HC 400, MENZERNA MC 2400, MENZERNA SFP 3800.`,
    },
    {
        id: 6,
        nombre: "Kit Pulido 3 Pasos Menzerna 1L",
        precio: 100000,
        img: "https://http2.mlstatic.com/D_NQ_NP_2X_896103-MLA53788027719_022023-F.webp",
        descripcion: `Kit Menzerna 3 pasos 1L: MENZERNA HC 400, MENZERNA MC 2400, MENZERNA SFP 3800.`,
    },
    {
        id: 7,
        nombre: "Sellador Ceramico Soft 99 H7 100ml",
        precio: 55000,
        img:"https://http2.mlstatic.com/D_NQ_NP_2X_855469-MLA53605969317_022023-F.webp",
        descripcion: `H-7 crea una superficie protectora sólida a base de óxido de silicio que posee una alta resistencia a las influencias abrasivas y químicas, añade un excelente brillo, por lo tanto es absolutamente seguro para una pintura y barniz que cubre y mantiene las propiedades de protección de hasta un año.`,
    },
    {
        id: 8,
        nombre: "Cera Soft99 Fusso Coat Colores Claros 200g",
        precio: 18000,
        img: "https://http2.mlstatic.com/D_NQ_NP_2X_821766-MLA49119190227_022022-F.webp",
        descripcion: `Sus polímeros, contienen una capacidad anti-incrustante suficiente, protegiendo eficazmente la superficie del coche contra la lluvia, la suciedad y otros residuos no deseados. Su capa dura y gruesa repele fuertemente el agua, ya que el agua fluye suavemente hacia abajo y hacia fuera de la superficie del coche.`,
    },
    {
        id: 9,
        nombre: "Cera Soft99 Fusso Coat Colores Oscuros 200g",
        precio: 18000,
        img: "https://http2.mlstatic.com/D_NQ_NP_2X_766780-MLA49118940488_022022-F.webp",
        descripcion: `Sus polímeros, contienen una capacidad anti-incrustante suficiente, protegiendo eficazmente la superficie del coche contra la lluvia, la suciedad y otros residuos no deseados. Su capa dura y gruesa repele fuertemente el agua, ya que el agua fluye suavemente hacia abajo y hacia fuera de la superficie del coche.`,
    },
    {
        id: 10,
        nombre: "Acondicionador Covers Matt Glabs 500ml",
        precio: 4500,
        img: "https://http2.mlstatic.com/D_NQ_NP_935034-MLA50434203214_062022-O.webp",
        descripcion: `Acondicionador formulado especificamente para superficies externas, su fórmula otorga brillo y protección dejando un acabado seco al tacto sobre partes plásticas y cubiertas.`,
    },
    {
        id: 11,
        nombre: "Pack 4 Paños Microfibra Laffitte",
        precio: 2500,
        img: "https://http2.mlstatic.com/D_NQ_NP_2X_797432-MLA44041279363_112020-F.webp",
        descripcion: `Este pack de 4 paños de microfibra Laffitte es ideal para mantener la limpieza en tu auto. Gracias a su material absorbente multiuso, podrás limpiar cualquier superficie de manera eficiente y sin dejar marcas. Con un tamaño de 30x30 cm, estos paños son perfectos para cubrir áreas amplias y llegar a los rincones más difíciles.`,
    },
    {
        id: 12,
        nombre: "Microfibra De Secado Premium Laffitte",
        precio: 4000,
        img: "https://http2.mlstatic.com/D_NQ_NP_826863-MLA51108218119_082022-O.webp",
        descripcion: `Medidas: 40cm x 60cm. Microfibra de alta densidad, gran capacidad de absorción. No raya, no deja marcas, ni pelusas. Limpia, seca y da brillo en un solo paso.`,
    },
    {
        id: 13,
        nombre: "Sellador Ceramico Soft 99 H7 50ml",
        precio: 35000,
        img: "https://http2.mlstatic.com/D_NQ_NP_2X_718611-MLA54286350748_032023-F.webp",
        descripcion: `H-7 crea una superficie protectora sólida a base de óxido de silicio que posee una alta resistencia a las influencias abrasivas y químicas, añade un excelente brillo, por lo tanto es absolutamente seguro para una pintura y barniz que cubre y mantiene las propiedades de protección de hasta un año.`,
    },
    {
        id: 14,
        nombre: "Kit 5 Pinceles Detallado Interior Vonixx",
        precio: 19500,
        img: "https://http2.mlstatic.com/D_NQ_NP_2X_979537-MLA47716660113_092021-F.webp",
        descripcion: `Kit de pinceles desarrollados para limpieza de coches, motos y repuestos en general. Compuesto por cerdas sintéticas con filamento cónico suave, flexible y duradero, es ideal para limpiar las partes internas más delicadas del vehículo o motocicleta.`,
    },
    {
        id: 15,
        nombre: "Royal Pads Ultimate 5 Finish",
        precio: 7000,
        img: "https://http2.mlstatic.com/D_NQ_NP_980285-MLA47366237356_092021-O.webp",
        descripcion: `La línea ULTIMATE son pads de pulido de celda abierta dedicadas para máquinas rotativas y Dual Action (Roto Orbital) y cualquier tipo de compuestos. La tecnología de celda abierta proporciona una ventilación mucho mejor, lo que permite una retención prolongada de las propiedades de pulido durante el trabajo. El perfil lateral de espuma cónica y el orificio central garantizan el más alto nivel de eficiencia y seguridad en el trabajo.`,
    }

]